# Generated by Django 4.0.10 on 2023-10-10 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_notice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support_detail',
            new_name='Support',
        ),
        migrations.AlterModelTable(
            name='support',
            table='support',
        ),
    ]
